name: taif
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Main dependencies
  image_picker: ^1.0.7
  url_launcher: ^6.3.0

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.2

  # Utils
  dash_chat_2: ^0.0.21
  http: ^1.2.1
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2

  # Notifications + Time
  flutter_local_notifications: ^17.2.0
  timezone: ^0.9.2

  # Communication + Sharing
  flutter_email_sender: ^7.0.0
  share_plus: ^11.1.0

  # Localization
  flutter_localizations:
    sdk: flutter

  # UI extras
  cupertino_icons: ^1.0.8

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/autism_screening_model.tflite

  fonts:
    - family: Lateef
      fonts:
        - asset: fonts/Lateef-Regular.ttf
